### PR TITLE
Isolator: Basic implementation

### PR DESCRIPTION
**Pull request by alexshgov**
## What it does
* Introduces **Adapters** (for now only AR supported)
* Introduces **Analyzers** (for now only HTTP analyzer supported)
* Adds `HTTP` analyzer
* Adds basic configuration support

### Configuration example
```ruby
Isolator.configure do |isolator|
  isolator.raise_errors = true
  isolator.logger = true
end
```

### CODE REVIEW

**Comment by palkan** [comment]
Hi, @alexshgov. Why did you close the PR?

**Comment by alexshgov** [comment]
Hi @palkan! I have a better idea, I will reopen it soon, thanks!

**Comment by alexshgov** [comment]
Here is it: https://github.com/palkan/isolator/pull/3

**Comment by palkan** [comment]
> I have a better idea, I will reopen it soon, thanks!

Okey) I was thinking about combine this PR with the first one (#1).

The plan is the following: I want to merge #1, then make some changes and then ask you (@alexshgov) to integrate Sniffer and Mailers analyzers into it. And then we'll be able to add more analyzers in parallel)

What do you, guys, think? /cc @TheSmartnik

**Comment by alexshgov** [comment]
@palkan, the plan sounds good to me. It seems the common interface introduced in #1 a much more flexible than mine (perhaps even too much flexible).

**Comment by TheSmartnik** [comment]
@palkan sounds good to me. One thing to note, If our requests are to be combined, I'd like to use configuration implementation from #3, hope it's alright.

@alexshgov Yeah, there is truth to it. However, It allows an easy way for end user to extend isolator.

**Pull request closed without merging**
